model_name: efficientnet-b5
validation: True

dataset:
    train: ../data/argumentation
    train_metadata: ../data/train_meta.json
    num_remove: 10
    valid: 0.15
    valid_epoch: 1
    transforms: [flip, erasing]

trainer:
    num_epoch: 30
    max_norm: 2

    argumentation:
        name: mixup
        probability: 0.5
        alpha: 1.0

    loss:
        name: adacos # ['arcface', 'adacos', 'curricularface']
        criterion: cross_entropy # ['cross_entropy', 'focal_loss']
        gamma_for_focal_loss: 2
        easy_margin: False
        s: 32
        m: 0.2

    optimizer:
        name: adamw # ['adam', 'adamw', 'sgd']
        lr_pretrained_model: 1.0e-4
        lr_linear_for_model_number: 1.0e-2
        lr_linear_for_category: 1.0e-2
        lr_linear_for_color: 1.0e-2
        lr_margin_penalty: 1.0e-2
        beta1: 0.9
        beta2: 0.999
        weight_decay: 5.e-4

    multi_task:
        model_number:
            flag: True
            loss: cross_entropy # ['cross_entropy', 'focal_loss']
            gamma: 2
            weight: 0.5
        category:
            flag: True
            loss: cross_entropy # ['cross_entropy', 'focal_loss']
            gamma: 2
            weight: 0.5
        color:
            flag: True
            loss: focal_loss # ['cross_entropy', 'focal_loss']
            gamma: 2
            weight: 0.5

    knn:
        method: nearest # ["center", "weighted", "nearest", None]
        metric: cosine # ['euclidean', 'cosine']
